"use client";

import { useEffect, useState, useCallback } from "react";
import Link from "next/link";
import { Loader2, ImageIcon } from "lucide-react";
import { toast } from "sonner";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { createClient } from "@/lib/supabase/client";
import type { Caption, HumorFlavor } from "@/lib/types";

const ALL_FLAVORS = "__all__";

export default function CaptionsPage() {
  const supabase = createClient();
  const [flavors, setFlavors] = useState<HumorFlavor[]>([]);
  const [selectedFlavor, setSelectedFlavor] = useState<string>(ALL_FLAVORS);
  const [captions, setCaptions] = useState<Caption[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchFlavors() {
      const { data } = await supabase
        .from("humor_flavors")
        .select("*")
        .order("slug");
      setFlavors(data ?? []);
    }
    fetchFlavors();
  }, [supabase]);

  const fetchCaptions = useCallback(async () => {
    setLoading(true);

    let query = supabase
      .from("captions")
      .select("*, images(*), humor_flavors(*)")
      .order("created_datetime_utc", { ascending: false })
      .limit(200);

    if (selectedFlavor !== ALL_FLAVORS) {
      query = query.eq("humor_flavor_id", Number(selectedFlavor));
    } else {
      query = query.not("humor_flavor_id", "is", null);
    }

    const { data, error } = await query;

    if (error) {
      toast.error("Failed to load captions", { description: error.message });
    }

    setCaptions((data as Caption[]) ?? []);
    setLoading(false);
  }, [supabase, selectedFlavor]);

  useEffect(() => {
    // Defer initial fetch to avoid synchronous state updates in effect.
    const timer = window.setTimeout(() => {
      void fetchCaptions();
    }, 0);
    return () => window.clearTimeout(timer);
  }, [fetchCaptions]);

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Captions</h1>
          <p className="text-muted-foreground">
            Browse captions generated by humor flavors.
          </p>
        </div>

        <Select value={selectedFlavor} onValueChange={(v) => setSelectedFlavor(v ?? ALL_FLAVORS)}>
          <SelectTrigger className="w-60">
            <SelectValue placeholder="Filter by flavor..." />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value={ALL_FLAVORS}>All Flavors</SelectItem>
            {flavors.map((f) => (
              <SelectItem key={f.id} value={String(f.id)}>
                {f.slug}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-20">
          <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
        </div>
      ) : captions.length === 0 ? (
        <div className="rounded-lg border border-dashed p-12 text-center">
          <h3 className="text-lg font-medium">No captions found</h3>
          <p className="mt-1 text-sm text-muted-foreground">
            {selectedFlavor !== ALL_FLAVORS
              ? "No captions for this flavor yet."
              : "No captions have been generated yet."}
          </p>
        </div>
      ) : (
        <div className="rounded-md border">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-16">Image</TableHead>
                <TableHead>Caption</TableHead>
                <TableHead className="w-40">Flavor</TableHead>
                <TableHead className="w-24 text-right">Likes</TableHead>
                <TableHead className="w-36">Created</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {captions.map((caption) => (
                <TableRow key={caption.id}>
                  <TableCell>
                    {caption.images?.url ? (
                      <img
                        src={caption.images.url}
                        alt=""
                        className="h-10 w-10 rounded object-cover"
                      />
                    ) : (
                      <div className="flex h-10 w-10 items-center justify-center rounded bg-muted">
                        <ImageIcon className="h-4 w-4 text-muted-foreground" />
                      </div>
                    )}
                  </TableCell>
                  <TableCell className="max-w-md">
                    <p className="truncate text-sm">{caption.content}</p>
                  </TableCell>
                  <TableCell>
                    {caption.humor_flavors ? (
                      <Link href={`/humor-flavors/${caption.humor_flavor_id}`}>
                        <Badge
                          variant="outline"
                          className="cursor-pointer hover:bg-muted"
                        >
                          {caption.humor_flavors.slug}
                        </Badge>
                      </Link>
                    ) : (
                      <span className="text-sm text-muted-foreground">—</span>
                    )}
                  </TableCell>
                  <TableCell className="text-right">{caption.like_count}</TableCell>
                  <TableCell className="text-sm text-muted-foreground">
                    {new Date(caption.created_datetime_utc).toLocaleDateString()}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      )}
    </div>
  );
}
